name: hello # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: interactive hello werld snap written in golang # 79 char long summary
description: |
    This is a learning exercise in writing an interactive "hello werld" program 
    in golang and packaging/publishing as a snap.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  hello:
    source: .
    plugin: go
    go-importpath: hello
  files:
    plugin: dump
    organize:
      ./src/usr/share*: usr/share/

apps: 
  hello:
    command: hello
